config/routes.rb
Rails.application.routes.draw do
  get 'actus', to: 'actus#index'
  get 'stats', to: 'stats#index'

  resources :events do
    get :cancel, on: :member
    get :preview, on: :collection, to: 'events#preview_create'
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    post :preview, on: :collection, to: 'orgas#preview_create'
    patch :preview, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',
        as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/controllers/moderations_controller.rb
# Event management life cycle
class ModerationsController < ApplicationController
  has_scope :city, :region, :locality, :tag, :daylimit, :year
  has_scope :near, type: :hash, using: %i[location distance]

  before_action :authenticate_user!
  before_action :set_moderation, only:
    %i[show edit preview update validate accept refuse destroy]
  before_action :generate_destroy_reason, only: :destroy
  rescue_from ActiveRecord::StaleObjectError, with: :locked

  def index
    @events = Event.unmoderated
    @orgas = Orga.unmoderated
  end

  def show; end

  def edit; end

  def validate; end

  def refuse; end

  def preview
    @moderation.attributes = moderation_params
    @moderation.valid?
    render action: :edit
  end

  # PATCH/PUT /moderations/1
  # PATCH/PUT /moderations/1.json
  def update
    respond_to do |format|
      if @moderation.update moderation_params
        format.html { redirect_to :moderations, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @moderation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accept/1
  # PATCH/PUT /accept/1.json
  def accept
    @moderation.update moderated: true
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  # DELETE /moderations/1
  # DELETE /moderations/1.json
  def destroy
    if @moderation.reason == 'r_0'
      @moderation.paper_trail.without_versioning :destroy
    else
      @moderation.destroy!
    end
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_moderation
    @event = Event.find params[:id]
    @moderation = @event
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def moderation_params
    params.expect event: %i[lock_version title start_time end_time repeat rule
                            description place_name address city region_id
                            locality url contact submitter tag_list reason]
  end

  def locked
    redirect_to edit_moderation_url(@moderation), alert: t('staleObjectError')
  end

  def generate_destroy_reason
    @moderation.attributes = moderation_params
    return if params[:reason] == 'r_4'

    @moderation.reason = t "moderations.refuse.reason_#{params[:reason]}_long"
  end
end

app/helpers/moderations_helper.rb
# Helper for the moderation views
module ModerationsHelper
end

app/views/moderations/_event.html.haml
%tr
  %td.title= event.title
  %td= display_date event
  %td.city= event.city
  %td.region= event.region
  %td= time_ago_in_words event.submission_time
  %th.actions{ rowspan: 1 + event.notes.size }
    = link_to validate_moderation_path event do
      %em.fa.fa-thumbs-up
      = t 'validate'
    \-
    = link_to refuse_moderation_path event do
      %em.fa.fa-thumbs-down
      = t 'refuse'
    %br
    = link_to new_moderation_note_path event, envoiParMail: :oui do
      %em.fa.fa-bullhorn
      = t '.askInfos'
    \-
    = link_to new_moderation_note_path event do
      %em.fa.fa-paperclip
      = t '.createNote'
  %td.view{ rowspan: 1 + event.notes.size }
    = link_to edit_moderation_path event do
      %em.fa.fa-arrow-circle-right

- event.notes.each do |note|
  %tr
    %td.note(colspan='5')
      = note.contents
      %em.author
        = t '.posted_by', author: note.author, date: l(note.date, format: :at)

app/views/moderations/_orga.html.haml
%tr
  %td.kind
    - if orga.kind
      %em.fa{ class: "fa-#{orga.kind.icon}",
              title: strip_tags(Kind.human_attribute_name("name_#{orga.kind.name}_html")) }
  %td.name= orga.name
  %td.city= orga.city
  %td.region= orga.region
  %td= time_ago_in_words orga.submission_time
  %th.actions
    = link_to validate_orga_path orga do
      %em.fa.fa-thumbs-up
      = t 'validate'
    \-
    = link_to cancel_orga_path orga do
      %em.fa.fa-thumbs-down
      = t 'refuse'
  %td.view
    = link_to edit_orga_path orga do
      %em.fa.fa-arrow-circle-right

app/views/moderations/edit.html.haml
%h2
  %em.fa.fa-edit
  = t '.title'

- if @moderation.moderated?
  %h3.warning
    %em.fa.fa-exclamation-triangle
    = t '.warning'

%fieldset
  %legend
    %em.fa.fa-eye
    = t '.preview'
  = render template: '/events/show'

%fieldset
  %legend
    %em.fa.fa-edit
    = t '.edit'
  = render '/events/form', event: @event

app/views/moderations/index.html.haml
%h2
  %em.fa.fa-gavel
  = title t '.title'

- if @orgas.present?
  %table.list
    %thead
      %tr
        %th(colspan='8')
          %h3
            %em.fa.fa-users
            = Orga.model_name.human.pluralize @orgas.count, I18n.locale

    - @orgas.group_by { |orga| orga.region }.each do |region, orgas|
      %thead
        %tr
          %td(colspan='8')
            %h4
              - if region&.code.present?
                = flag_icon region.code
                = t region.code.upcase, scope: :countries
              - else
                = orgas[0].region
        %tr
          %th.name(colspan='2')= Orga.human_attribute_name :name
          %th.city= Orga.human_attribute_name :city
          %th.region= Orga.human_attribute_name :region
          %th= Orga.human_attribute_name :submission_time
          %th.view(colspan='3')

      %tbody= render partial: 'orga', collection: orgas

    %tfoot
      %tr
        %td(colspan='8')
          :markdown
            #{t '.rules'}

- if @orgas.present? && @events.present?
  %hr

- if @events.present?
  %table.list
    %thead
      %tr
        %th(colspan='8')
          %h3
            %em.fa.fa-calendar
            = Event.model_name.human.pluralize @events.count, I18n.locale

    - @events.group_by { |event| event.region }.each do |region, events|
      %thead
        %tr
          %td(colspan='8')
            %h4
              - if region&.code.present?
                = flag_icon region.code
                = t region.code.upcase, scope: :countries
              - else
                = events[0].region
        %tr
          %th.title= Event.human_attribute_name :title
          %th
            = Event.human_attribute_name :start_time
            \-
            = Event.human_attribute_name :end_time
          %th.city= Event.human_attribute_name :city
          %th.region= Event.human_attribute_name :region
          %th= Event.human_attribute_name :submission_time
          %th.view(colspan='3')

      %tbody= render partial: 'event', collection: events

    %tfoot
      %tr
        %td(colspan='8')
          :markdown
            #{t '.rules'}

%fieldset.actions
  = link_to edit_user_registration_path do
    %em.fa.fa-lock
    = t('change_my_password', scope: 'devise.passwords.edit')
  \-
  = link_to 'admin' do
    %em.fa.fa-user-gear
    Admin
  \-
  = link_to destroy_user_session_path, method: :delete do
    %em.fa.fa-sign-out-alt
    = t 'logout'

app/views/moderations/refuse.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

= form_for @moderation, url: { action: :destroy },
                        html: { method: :delete } do |f|
  .field.required{ title: t('.reason_r_0_long') }
    = f.label :reason
    %span.radios
      = radio_button_tag :reason, :r_0, params[:event] == 'reason_r_0'
      = label_tag :reason_r_0, t('.reason_r_0')
      = radio_button_tag :reason, :r_1, params[:event] == 'reason_r_1'
      = label_tag :reason_r_1, t('.reason_r_1')
      = radio_button_tag :reason, :r_2, params[:event] == 'reason_r_2'
      = label_tag :reason_r_2, t('.reason_r_2')
      = radio_button_tag :reason, :r_3, params[:event] == 'reason_r_3'
      = label_tag :reason_r_3, t('.reason_r_3')
      = radio_button_tag :reason, :r_4,
                         params[:event] == 'reason_r_4' || !params[:event]
      = label_tag :reason_r_4, t('.reason_r_4')

  .field.reason
    = f.label :reason
    = f.text_area :reason, cols: 40, rows: 5

  .actions
    = link_to moderations_path do
      %em.fa.fa-arrow-left
      = t '.ko'

    = button_tag do
      %em.fa.fa-thumbs-down
      = t '.ok'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Event.model_name.human
  = render template: '/events/show'

app/views/moderations/validate.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

- if @event.locality?
  %h2.warning= t '.warning'

= form_for @moderation, url: { action: :accept }, html: { method: :put } do |f|
  .actions
    = link_to moderations_path do
      %em.fa.fa-arrow-left
      = t '.ko'

    = f.button do
      %em.fa.fa-thumbs-up
      = t '.ok'

- if @event.repeat.positive?
  %fieldset
    %legend
      %em.fa.fa-redo-alt
      = Event.human_attribute_name :repeat

    %h3= t '.repeat_helper', count: @event.repeat

    %p.rule
      = Event.human_attribute_name :rule
      = t @event.rule, scope: 'activerecord.attributes.event.rule_values'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Event.model_name.human
  = render template: '/events/show'