config/routes.rb
Rails.application.routes.draw do
  get 'actus', to: 'actus#index'
  get 'stats', to: 'stats#index'

  resources :events do
    get :cancel, on: :member
    get :preview, on: :collection, to: 'events#preview_create'
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    post :preview, on: :collection, to: 'orgas#preview_create'
    patch :preview, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',
        as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/models/orga.rb
# Organisations related to this agenda
class Orga < ApplicationRecord
  include Addressable

  acts_as_taggable
  strip_attributes
  has_paper_trail ignore: %i[last_updated secret submitter decision_time
                             lock_version latitude longitude]

  belongs_to :kind
  has_many :actus, dependent: :destroy

  def self.ransackable_associations(_auth_object = nil)
    %w[kind region actus]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name kind_id region_id active city description updated_at]
  end

  validates_with AntispamValidator, fields: %i[name submitter], on: :create

  validates :name, presence: true
  validates :url, format: %r{\Ahttps?://.*\..*\z}
  validates :diaspora, allow_blank: true, format: %r{\Ahttps?://.*\..*\z}
  validates :feed, allow_blank: true, format: %r{\Ahttps?://.*\..*\z}
  validates :contact, allow_blank: true, email: true
  validates :submitter, allow_blank: true, email: true

  default_scope { includes :region, :kind, :tags }
  scope :active, ->(value = true) { where active: value }
  scope :inactive, ->(value = false) { where active: value }
  scope :moderated, -> { where moderated: true }
  scope :unmoderated, -> { where moderated: false }
  scope :with_feed, -> { where.not(feed: '') }

  # Only present to simplify maps_controller, to have the same scopes as events
  scope :locality, ->(_locality) {}
  scope :daylimit, ->(_nb) {}
  scope :future, -> {}
  scope :period, ->(_year, _week) {}
  scope :kind, ->(kind) { where kind: kind }
  scope :tag, ->(tag) { tagged_with tag }

  def as_json(options = {})
    super(options.merge(except: [:secret]))
  end

  before_validation do
    self.secret ||= SecureRandom.urlsafe_base64(32)[0...32]
    self.submission_time ||= Time.zone.now
  end

  after_create do
    send_secret
    # Send email to moderators when an new orga is received
    ModerationorgaMailer.create(self).deliver_now
  end

  after_update do
    send_secret if saved_change_to_secret? || saved_change_to_submitter?

    if saved_change_to_moderated?
      # Send an acceptation mail to its author
      OrgaMailer.accept(self).deliver_now if submitter.present?

      # Send an acceptation mail to moderators
      ModerationorgaMailer.accept(self).deliver_now

    else
      # Send an update mail to its author
      OrgaMailer.update(self).deliver_now if submitter.present?

      # Send an update mail to moderators
      ModerationorgaMailer.update(self).deliver_now
    end
  end

  before_destroy do
    OrgaMailer.destroy(self).deliver_now if submitter.present?
    # Send email to moderators when deleted
    ModerationorgaMailer.destroy(self).deliver_now
  end

  def send_secret
    OrgaMailer.create(self).deliver_now if submitter.present? && secret.present?
  end

  def name_as_tag
    name.delete_prefix('L\'').gsub(/[\s*'.]/, '-').delete ':'
  end

  def to_s
    name
  end
end

app/controllers/orgas_controller.rb
# Groups life cycle
class OrgasController < ApplicationController
  has_scope :city, :region, :tag
  has_scope :near, type: :hash, using: %i[location distance]
  has_scope :active, type: :boolean, default: true, allow_blank: true

  before_action :set_orga, if: -> { params[:id].present? }
  before_action :authenticate_user!, if: -> { params[:id].present? },
                                     unless: :check_secret,
                                     except: %i[show]

  def index
    @unfiltered_orgas = apply_scopes Orga.moderated
    @search = @unfiltered_orgas.ransack params[:q]
    @search.sorts = 'updated_at desc' if @search.sorts.empty?
    @orgas = @search.result
    @orgas = @orgas.page(params[:page]).without_count unless params[:format] == 'opml'
  end

  def show
    @events_future = Event.moderated.future.tag @orga.name_as_tag
    @events_past = Event.moderated.past.tag @orga.name_as_tag
  end

  # GET /orgas/new
  def new
    @orga = Orga.new region_id: params[:region]
  end

  # POST /orgas/preview
  def preview_create
    @orga = Orga.new orga_params
    @orga.valid?
    render action: :new
  end

  # POST /orgas
  # POST /orgas.json
  def create
    @orga = Orga.new orga_params
    respond_to do |format|
      if @orga.save
        format.html { redirect_to orga_path(@orga, secret: @orga.secret), notice: t('.ok') }
        format.json { render action: :show, status: :created, location: @orga }
      else
        format.html { render action: :new }
        format.json { render json: @orga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgas/1/preview
  def preview
    @orga.attributes = orga_params
    @orga.valid?
    render action: :edit
  end

  # PATCH/PUT /orgas/1
  # PATCH/PUT /orgas/1.json
  def update
    respond_to do |format|
      if @orga.update orga_params
        format.html { redirect_to @orga, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @orga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accept/1
  # PATCH/PUT /accept/1.json
  def accept
    @orga.update moderated: true
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  # DELETE /orgas/1
  # DELETE /orgas/1.json
  def destroy
    @orga.destroy
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_orga
    @orga = Orga.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through
  def orga_params
    params.expect orga: %i[lock_version kind_id name description place_name
                           address city department region_id url diaspora
                           feed contact submitter tag_list active]
  end

  # Check that you can only edit an existing event if you know its secret
  def check_secret
    %w[validate refuse].exclude?(action_name) &&
      (!@orga.secret || @orga.secret == params[:secret])
  end
end

app/helpers/orgas_helper.rb
# Helper for the orga views
module OrgasHelper
  def orga_meta(orga)
    return if orga.new_record?

    set_meta_tags \
      keywords: orga.tags.join(' '),
      DC: { title: orga.name },
      geo: geo(orga),
      canonical: orga_url(orga)
  end

  def geo(orga)
    position = [orga.latitude, orga.longitude].compact_blank
    {
      placename: orga.city, region: orga.region.try(:to_s),
      position: position.join(';'),
      ICBM: position.join(', ')
    }
  end
end

app/views/orgas/_aside.html.haml
%aside
  %h2
    %em.fa.fa-link
    = t '.links'

  %ul.fa-ul
    %li
      = link_to orgas_path q: params[:q], page: params[:page] do
        %em.fa.fa-li.fa-arrow-left
        = Orga.model_name.human.pluralize I18n.locale
    %li
      = link_to tag_path @orga.name_as_tag do
        %em.fa.fa-li.fa-tag
        = Event.model_name.human.pluralize I18n.locale
    %li
      = link_to events_path tag: @orga.name_as_tag do
        %em.fa.fa-li.fa-calendar
        Agenda
    %li
      = link_to events_path format: :rss, tag: @orga.name_as_tag do
        %em.fa.fa-li.fa-rss
        RSS
    %li
      = link_to events_path format: :ics, tag: @orga.name_as_tag do
        %em.fa.fa-li.fa-th-list
        iCal
    %li
      = link_to maps_path tag: @orga.name_as_tag do
        %em.fa.fa-li.fa-map-marker
        OpenStreetMap
    %li
      = link_to maps_path format: :json, tag: @orga.name_as_tag do
        %em.fa.fa-li.fa-dot-circle
        GeoJSON

  - if @orga.secret.nil? || user_signed_in?
    %h2
      %em.fa.fa-wrench
      = t '.actions'
    %ul.fa-ul
      %li
        = link_to edit_orga_path @orga do
          %em.fa.fa-li.fa-edit
          = t '.edit'
      - if user_signed_in?
        %li
          = link_to cancel_orga_path @orga do
            %em.fa.fa-li.fa-thumbs-down
            = t '.cancel'
  - elsif params[:secret]
    %h2
      %em.fa.fa-wrench
      = t '.actions'
    %ul.fa-ul
      %li
        = link_to edit_orga_path @orga, secret: params[:secret] do
          %em.fa.fa-li.fa-edit
          = t '.edit'

app/views/orgas/_favicon.html.haml
- if orga.url.present? && orga.url.match(/^http/) && orga.url.exclude?('facebook')
  = image_tag "#{orga.url}/favicon.ico", alt: '', class: :favicon

app/views/orgas/_form.html.haml
= form_for orga do |f|
  - if orga.persisted?
    = hidden_field_tag :secret, params[:secret]

  - if orga.errors.any?
    #flash-messages
      - orga.errors.full_messages.each do |msg|
        %p.flash.alert= msg

  .field.kind.required
    = f.label :kind
    %span.radios
      - Kind.find_each do |kind|
        = f.radio_button :kind_id, kind.id, required: true
        = f.label "kind_id_#{kind.id}" do
          %em.fa{ class: "fa-#{kind.icon}" }
          = t "#{kind.name}_html", scope: 'activerecord.attributes.kind/name'
  .field.name.required
    = f.label :name
    = f.text_field :name, required: true
  .field.place_name
    = f.label :place_name
    = f.text_field :place_name
  .helper
    :markdown
      #{t '.address_helper_html'}
  .field.address
    = f.label :address
    = f.text_field :address
  .field.city
    = f.label :city
    = f.text_field :city, list: :cities
    %datalist#cities
      - Event.group(:city).order('1 desc').count.each do |r|
        %option= r[0]
  .field.region.required
    = f.label :region, for: "orga_region_id_#{params[:region]}"
    = render partial: '/regions/selector', locals: { f: f }

  .field.description{ title: t('.description_helper') }
    = f.label :description
    = f.text_area :description, class: :description

  .field.url.required{ title: t('.url_helper') }
    = f.label :url
    = f.url_field :url, required: true, placeholder: 'Ex: https://april.org'
  - if orga.try(:diaspora?)
    .field.diaspora
      = f.label :diaspora
      = f.url_field :diaspora
  .field.feed{ title: t('.feed_helper') }
    = f.label :feed
    = f.url_field :feed, placeholder: 'Ex: https://april.org/index.rss'
  .field.contact{ title: t('.contact_helper') }
    = f.label :contact
    = f.email_field :contact
  .field.submitter{ title: t('.submitter_helper') }
    = f.label :submitter
    = f.email_field :submitter

  .field.tags{ title: t('.tags_helper') }
    = f.label :tags, for: 'orga_tag_list_tag'
    = f.text_field :tag_list, value: f.object.tag_list.join(' ')

  .field.active
    = f.label :active
    = f.check_box :active

  .actions
    = f.button formaction: url_for(action: orga.new_record? ? :preview_create : :preview) do
      %em.fa.fa-eye
      = t '.visualise'
    = f.button do
      %em.fa.fa-check
      = t '.save'

app/views/orgas/_orga.html.haml
%tr{ class: orga.active ? 'active' : 'inactive' }
  %td.kind
    - if orga.kind
      %em.fa{ class: "fa-#{orga.kind.icon}",
              title: strip_tags(Kind.human_attribute_name("name_#{orga.kind.name}_html")) }
  %td.name
    = orga.name
    = render partial: '/orgas/favicon', locals: { orga: orga }
  %td.city= orga.city
  %td.region= orga.region
  %td.flag= flag_icon orga.region.flag
  %td.updated_at
    = l orga.updated_at.to_date if orga.updated_at.present?
  %td.tags{ title: orga.tags.join(' ')}
    - if orga.tags.size > 1
      %em.fa.fa-tags
    - elsif orga.tags.size.positive?
      %em.fa.fa-tag
  %td.url
    - if orga.url
      = link_to orga.url, target: '_blank', rel: 'noopener', aria: { label: Orga.human_attribute_name(:url) } do
        %em.fa.fa-external-link-alt
  %td.feed
    - if orga.feed
      = link_to orga.feed, target: '_blank', rel: 'noopener', aria: { label: Orga.human_attribute_name(:feed) } do
        - if orga.actus.empty?
          %em.fa.fa-chain-broken
        - else
          %em.fa.fa-feed
  %td.view
    = link_to orga_path(orga, q: params[:q].permit, page: params[:page]), aria: { label: t('show') } do
      %em.fa.fa-arrow-circle-right

app/views/orgas/_search.html.haml
= search_form_for Orga.ransack(params[:q]) do |f|
  = f.label :ransack, t('.label')
  = f.search_field :name_or_city_or_description_or_region_name_cont_any,
                   id: :q_ransack, size: 16,
                   placeholder: t('.title', entity: Orga.model_name.human),
                   title: t('.helper', entity: Orga.model_name.human),
                   autofocus: true
  = f.button class: :search, 'aria-label': t('.label') do
    %em.fa.fa-search

app/views/orgas/_types.haml
- params[:q] = {} if params[:q].nil?
- p = params[:q].clone.permit

%ul.actions
  -# The reorder and specific count are required for the "near" scope
  - @unfiltered_orgas.reorder('').group(:kind).count(:all).each do |kind, count|
    - p[:kind_id_eq] = kind&.id.to_s
    - active_link = params[:q][:kind_id_eq] == kind&.id.to_s

    %li{ title: strip_tags(Kind.human_attribute_name("name.#{kind&.name}_html")),
         class: active_link ? 'active' : '' }
      = link_to orgas_url(q: p, active: params[:active]), class: 'button' do
        %em.fa{ class: "fa-#{kind&.icon}" }
        = count
        - if active_link
          \-
          = t "#{kind&.name}_html", scope: 'activerecord.attributes.kind/name'

  - count = @unfiltered_orgas.count :all
  - if count.positive?
    %li{ title: "#{Kind.human_attribute_name('active').pluralize}?" }
      - p[:kind_id_eq] = params[:q][:kind_id_eq]
      \/
      = link_to orgas_url(q: p, active: params[:active].present? && params[:active] != 'true'), class: 'button' do
        - if params[:active].nil? || params[:active] == 'true'
          %em.fa.fa-heartbeat
        - else
          %em.fa.fa-heart-broken
        = count

app/views/orgas/cancel.html.haml
%h2
  %em.fa.fa-trash-alt
  = t '.title'

- if @orga.moderated?
  %h3.warning= t '.already_moderated'

%fieldset
  = form_for @orga, method: :delete do |f|
    = hidden_field_tag :secret, params[:secret]
    %h2= t '.confirm'

    .actions
      = link_to @orga do
        %em.fa.fa-arrow-left
        = t '.ko'
      = f.button do
        %em.fa.fa-check
        = t '.ok'

%fieldset
  %legend= Orga.model_name.human
  = render template: '/orgas/show'

app/views/orgas/edit.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

%fieldset
  %legend
    %em.fa.fa-eye
    = t '.preview'
  = render template: '/orgas/show'

%fieldset
  %legend
    %em.fa.fa-edit
    = t '.edit'
  = render 'form', orga: @orga

app/views/orgas/index.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

= render 'search'

= render 'types'

%table.list
  %thead
    %th.name(colspan='2')= sort_link @search, :name
    %th.city= sort_link @search, :city
    %th.region(colspan='2')
      = sort_link @search, :region_name, Orga.human_attribute_name(:region)
    %th.updated_at= sort_link @search, :updated_at

  %tbody= render @orgas

  %tfoot
    %tr
      %th(colspan='10')
        = link_to_next_page @orgas, t('views.pagination.next'), remote: true

.links
  - p = params.permit :city, :region, :tag, near: {}
  = link_to orgas_path(:rss, p) do
    %em.fa.fa-rss
    = t 'rss', scope: 'pages.filter'
  = link_to orgas_path(:opml, p) do
    %em.fa.fa-square-rss
    OPML

app/views/orgas/new.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

- if @orga.description
  %fieldset
    %legend
      %em.fa.fa-eye
      = t '.preview'
    = render template: '/orgas/show'

%fieldset
  %legend
    %em.fa.fa-edit
    = t '.edit'
  = render 'form', orga: @orga

app/views/orgas/show.html.haml
- orga_meta @orga

%h2
  - if @orga.kind
    %em.fa{ class: "fa-#{@orga.kind.icon}",
      title: strip_tags(Kind.human_attribute_name("name_#{@orga.kind.name}_html")) }
  = title @orga.name
  = render partial: '/orgas/favicon', locals: { orga: @orga }

= render 'aside' if [controller_name, action_name] == %w[orgas show]

%p.full_address
  = [@orga.place_name,
    @orga.address,
    @orga.city,
    t(@orga.region&.code,
    scope: :countries,
    default: @orga.region)].compact.join ', '

- if @orga.latitude && @orga.longitude
  .orga#map{ data: { url: maps_path(format: :json).to_s,
    latitude: @orga.latitude.to_s,
    longitude: @orga.longitude.to_s,
    icon: @orga.kind&.icon } }

.description
  = description sanitize @orga.description,
    tags: %w[p h1 h2 h3 h4 br table tr th td ul ol li a strong b em i img sub sup span],
    attributes: %w[href src width height style title name id]

%h3
  %em.fa.fa-info-circle
  = t '.infos'
%dl
  - if @orga.url.present?
    %dt.url
      %em.fa.fa-external-link-alt
      = Orga.human_attribute_name :url
    %dd= link_to @orga.url, @orga.url
  - if @orga.diaspora.present?
    %dt.diaspora<
      = Orga.human_attribute_name :diaspora
      %em.fa
    %dd= link_to @orga.diaspora, @orga.diaspora
  - if @orga.feed.present?
    %dt.feed
      %em.fa.fa-rss
      = Orga.human_attribute_name :feed
    %dd= link_to @orga.feed, @orga.feed
    %dt.actus
      %em.fa.fa-feed
      = Actu.model_name.human.pluralize I18n.locale
    %dd
      = link_to actus_path orga: @orga do
        = Actu.where(orga: @orga).count
  - if @orga.contact.present?
    %dt.contact
      %em.fa.fa-envelope
      = Event.human_attribute_name :contact
    %dd= mail_to @orga.contact, nil,
      encode: (request.format == 'text/html' ? :javascript : nil),
      replace_at: ' CHEZ ', replace_dot: ' POINT '
  - if @orga.tags&.any?
    %dt.tags
      %em.fa.fa-tags
      = Event.human_attribute_name :tags
    %dd
      - @orga.tags.each do |tag|
        = link_to tag, tag_path(tag.name), rel: :tag
  %dt.active
    %em.fa.fa-heartbeat
    = Orga.human_attribute_name :active
  %dd= t @orga.active.to_s
  - if @orga.updated_at
    %dt.updated_at
      %em.fa.fa-calendar
      = Orga.human_attribute_name :updated_at
    %dd= l @orga.updated_at.to_date, format: :long

  - if @events_future&.any?
    %dt.future
      %em.fa.fa-forward
      = t '.future'
    %dd
      = link_to tag_path @orga.name_as_tag do
        = t '.count', count: @events_future.count
  - if @events_future && @events_past.any?
    %dt.past
      %em.fa.fa-backward
      = t '.past'
    %dd
      = link_to tag_path(@orga.name_as_tag, anchor: 'past') do
        = t '.count', count: @events_past.count

app/views/orgas/show.text.haml
==============================================================================
!= display_attr @orga, :kind,
               strip_tags(t("#{@orga.kind&.name}_html", scope: 'activerecord.attributes.kind/name'))
!= display_attr @orga, :name
- if @orga.place_name?
  != display_attr @orga, :place_name
- if @orga.address?
  != display_attr @orga, :address
- if @orga.place_name?
  != display_attr @orga, :city
!= display_attr @orga,
               :region,
               t(@orga.region&.code, scope: :countries, default: @orga.region.name)
- if @orga.url?
  != display_attr @orga, :url
- if @orga.diaspora?
  != display_attr @orga, :diaspora
- if @orga.feed?
  != display_attr @orga, :feed
- if @orga.contact?
  != display_attr @orga, :contact
- if @orga.submitter?
  != display_attr @orga, :submitter
- if @orga.tag_list.present?
  != display_attr @orga, :tags, @orga.tag_list
!= display_attr @orga, :active, t(@orga.active.to_s)
\
!= to_markdown @orga.description, 78
==============================================================================

app/views/orgas/validate.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

= form_for @orga, url: { action: :accept }, html: { method: :put } do |f|
  .actions
    = link_to moderations_path do
      %em.fa.fa-arrow-left
      = t '.ko'

    = f.button do
      %em.fa.fa-thumbs-up
      = t '.ok'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Orga.model_name.human
  = render template: '/orgas/show'