config/routes.rb
Rails.application.routes.draw do
  get 'actus', to: 'actus#index'
  get 'stats', to: 'stats#index'

  resources :events do
    get :cancel, on: :member
    get :preview, on: :collection, to: 'events#preview_create'
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    post :preview, on: :collection, to: 'orgas#preview_create'
    patch :preview, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',
        as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/models/event.rb
require 'schedule'

# This is the central ADL class, where are managed all events
class Event < ApplicationRecord
  extend SimpleCalendar
  include Addressable
  include Schedule

  acts_as_taggable
  strip_attributes
  has_paper_trail ignore: %i[last_updated lock_version secret submitter
                             decision_time latitude longitude]

  # This is the eventual scheduled first event
  belongs_to :event, optional: true
  has_many :notes, dependent: :destroy
  has_many :events, dependent: :destroy

  def self.ransackable_associations(_auth_object = nil)
    %w[region]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[region_id title city description]
  end

  validates_with AntispamValidator, fields: %i[title submitter], on: :create

  validates :title, presence: true
  validate :end_after_start
  RULES = %w[daily weekly monthly monthly_day].freeze
  validates :rule, inclusion: RULES, allow_nil: true
  validates :description, presence: true
  validates :url, allow_nil: true, format: %r{\Ahttps?://.*\..*\z}
  validates :contact, email: true, allow_nil: true
  validates :submitter, email: true

  # Mechanism to store some reason which can be used when sending notifications
  attr_accessor :reason

  before_create EventCallbacks
  after_create EventCallbacks

  before_update EventCallbacks
  after_update EventCallbacks

  after_destroy EventCallbacks

  scope :moderated, ->(*) { where moderated: true }
  scope :unmoderated, ->(*) { where moderated: false }
  scope :past, -> { where start_time: ..Time.zone.now }
  scope :future, -> { where end_time: Time.zone.now.. }
  scope :daylimit, ->(nb) { where end_time: ..nb.to_i.days.from_now }
  scope :year, (lambda do |year|
    where '? <= end_time and start_time <= ?',
          Date.new(year.to_i, 1, 1).beginning_of_week,
          Date.new(year.to_i, 12, 31).end_of_week.end_of_day
  end)
  scope :start_date, (lambda do |start_date|
    where '? <= end_time and start_time <= ?',
          (start_date || Time.zone.today).to_date.beginning_of_month.beginning_of_week,
          (start_date || Time.zone.today).to_date.end_of_month.end_of_week.end_of_day
  end)
  scope :period, (lambda do |year, week|
    start_date = Date.commercial year.to_i, (week || (Time.zone.today + 7.days).cweek).to_i
    where '? <= end_time and start_time <= ?', start_date, start_date.end_of_week.end_of_day
  end)
  scope :locality, ->(locality) { where locality: locality }
  scope :tag, ->(tag) { tagged_with tag }

  before_validation on: :create do
    self.submission_time = Time.zone.now
    self.decision_time = Time.zone.now
  end

  def hashtags
    tags.map { |tag| "##{tag.name.tr('-', '_').camelize :lower}" }.join ' '
  end

  def to_s
    [start_time.to_date, city ? "#{city}:" : nil, title, hashtags].compact.join(' ')
  end

  def as_json(options = {})
    super(options.merge(except: [:secret]))
  end

  private

  def end_after_start
    errors.add :end_time, :before_start if end_time && start_time && end_time < start_time
  end
end

app/controllers/events_controller.rb
# Event life cycle
# This is a central part to this project
class EventsController < ApplicationController
  has_scope :start_date, default: nil, allow_blank: true, if: :monthly?
  has_scope :city, :region, :locality, :tag, :daylimit, :year
  has_scope :near, type: :hash, using: %i[location distance]
  has_scope :future, type: :boolean, default: true, only: [:index], if: :future?

  before_action :set_event, if: -> { params[:id].present? }
  before_action :check_secret, only: %i[edit preview update destroy]
  skip_before_action :verify_authenticity_token, only: [:preview_create]
  rescue_from ActiveRecord::StaleObjectError, with: :locked

  def index
    # The 3000 limit is purely arbitrary...
    @events = apply_scopes(Event).moderated.includes(:tags).limit(3000).order(start_time: :asc)
    @events = @events.limit(20).order(id: :desc) if params[:format] == 'rss'
  end

  # GET /events/new
  def new
    params[:event] ||= { region_id: session[:region] }
    @event = Event.new event_params
  end

  def edit; end

  # GET/POST /events/preview
  def preview_create
    @event = Event.new event_params
    @event.valid?
    render action: :new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new event_params
    respond_to do |format|
      if @event.save
        format.html { redirect_to event_path(@event, secret: @event.secret), notice: t('.ok') }
        format.json { render action: :show, status: :created, location: @event }
      else
        format.html { render action: :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1/preview
  def preview
    @event.attributes = event_params
    @event.valid?
    render action: :edit
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update event_params
        format.html { redirect_to @event, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.reason = params[:event][:reason]
    @event.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions
  def set_event
    @event = Event.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through
  def event_params
    params.expect event: %i[lock_version title start_time end_time repeat rule
                            description place_name address city region_id
                            locality url contact submitter tag_list]
  end

  def locked
    redirect_to edit_event_url(@event, secret: @event.secret),
                alert: t('staleObjectError')
  end

  # Check that you can only edit an existing event if you know its secret
  def check_secret
    redirect_to :root, alert: t('events.edit.forbidden') unless params[:secret] == @event.secret
  end

  # Should the future scope be applied?
  # Only on non html pages...
  def future?
    params[:format].present? && params[:format] != 'html'
  end

  # To limit the results to a month view
  def monthly?
    (params[:format].blank? || params[:format] == 'html') && params[:year].blank?
  end
end

app/helpers/events_helper.rb
# Helper for the event views
module EventsHelper
  TAGS_TO_SANITIZE = %w[p br h1 h2 h3 h4 table tr th td ul ol li a strong b em i].freeze

  def events_meta
    set_meta_tags \
      prev: prev_url, next: next_url,
      description: t('layouts.application.subtitle'),
      keywords: params[:tag],
      DC: {
        title: t('layouts.application.title'),
        subject: t('layouts.application.subtitle'),
        publisher: 'april'
      }
  end

  def event_meta(event)
    return if event.new_record?

    set_meta_tags \
      keywords: event.tag_list,
      image_src: first_image(event.description),
      DC: { title: event.title, date: event.start_time.to_s },
      og: { image: first_image(event.description), title: event.title, type: 'website' },
      geo: geo(event),
      canonical: event_url(event)
  end

  def display_date(event)
    if event.start_time.to_date == event.end_time.to_date
      display_sameday event
    else
      display_multi_days event
    end
  end

  def display_sameday(event)
    t 'date.formats.same_day',
      date: l(event.start_time.to_date, format: :at),
      start: l(event.start_time, format: :hours),
      end: l(event.end_time, format: :hours)
  end

  def display_multi_days(event)
    t 'date.formats.period', start: l(event.start_time, format: :at), end: l(event.end_time, format: :at)
  end

  # Select the events to display in a month
  def month_events(events, date)
    events.select { |e| (e.start_time.to_date..e.end_time.to_date).cover? date }
  end

  def display_attr(item, label, value = item[label])
    # return unless value
    item.class.human_attribute_name(label).rjust(12) + " #{value}"
  end

  # Using kramdown, let's parse the html and render it as markdown text
  def to_markdown(desc, line_width = -1)
    return '' if desc.blank?

    post Kramdown::Document.new(pre(desc), input: :html, line_width: line_width)
                           .to_kramdown
  end

  # Copy some attributes to duplicate an event
  def duplicate(event)
    event.attributes
         .slice(*%w[title start_time end_time place_name address city region_id locality description url contact])
         .merge(tag_list: event.tags.join(' '))
  end

  private

  def prev_url
    if params[:year]
      url_for year: params[:year].to_i - 1
    else
      url_for start_date: (params[:start_date] || Time.zone.today).to_date.beginning_of_month.beginning_of_week.prev_day
    end
  end

  def next_url
    if params[:year]
      url_for year: params[:year].to_i + 1
    else
      url_for start_date: (params[:start_date] || Time.zone.today).to_date.end_of_month.end_of_week.next_day
    end
  end

  def first_image(description)
    Nokogiri::HTML.fragment(description).css('img').first.try(:[], :src)
  end

  def geo(event)
    position = [event.latitude, event.longitude].compact_blank
    {
      placename: event.city, region: event.region.try(:to_s),
      position: position.join(';'), ICBM: position.join(', ')
    }
  end

  # Cleaner html elements, to correct things like <em> test</em>
  def pre(desc)
    desc = sanitize desc, tags: TAGS_TO_SANITIZE, attributes: %w[href]

    desc.gsub(/<(strong|em|b|i)>\s+/, ' <\1>')
        .gsub(%r{\s+</(strong|em|b|i)>}, '</\1> ')
        .gsub(/\s+([,.:])/, '\1')
        .gsub(%r{<br/?></}, '</') # Remove extraneous breaks
        .remove(%r{<(strong|em|b|i)\s*/>})
        .remove(%r{<(strong|em|b|i)>\s*</(strong|em|b|i)>})
        .remove(%r{<(strong|em|b|i)>\s*</(strong|em|b|i)>}) # Twice to remove eventually imbricated ones
  end

  def post(generated)
    generated.gsub(/^#+\s+(.*)/, '**\1**') # Title transformed into strong
             .gsub('****', '**')
             .gsub(/\\(["'])/, '\1') # Remove slash before quotes
             .remove(/[[:blank:]]+$/) # Remove extraneous spaces
             .remove(/{::}/) # Markdown artefact
             .remove(/^\*\*$\n/)
  end
end

app/views/events/_aside.html.haml
%aside
  - if event.region.present? && event.region.orgas.present?
    %h2
      = link_to orgas_path region: event.region do
        %em.fa.fa-users
        = t '.orga-list'
    %ul.fa-ul
      - event.region.orgas.select(&:active).each do |orga|
        %li
          = link_to orga do
            - if orga.kind
              %em.fa.fa-li{ class: "fa-#{orga.kind.icon}",
                            title: strip_tags(Kind.human_attribute_name("name_#{orga.kind.name}_html")) }
            = orga.name
            = render partial: '/orgas/favicon', locals: { orga: orga }

  %h2
    %em.fa.fa-wrench
    = t '.actions'
  %ul.fa-ul
    %li
      = link_to event_path event, protocol: :webcal, format: :ics do
        %em.fa.fa-li.fa-calendar
        = t '.add_to_calendar'
    %li
      = link_to preview_events_path(event: duplicate(event)),
                method: :post do
        %em.fa.fa-li.fa-copy
        = t '.copy'
    - if user_signed_in?
      %li
        = link_to edit_moderation_path event do
          %em.fa.fa-li.fa-edit
          = t '.edit'
      %li
        = link_to cancel_event_path event, secret: event.secret do
          %em.fa.fa-li.fa-thumbs-down
          = t '.cancel'
    - elsif params[:secret]
      %li
        = link_to edit_event_path event, secret: params[:secret] do
          %em.fa.fa-li.fa-edit
          = t '.edit'

app/views/events/_event.haml
%li.event{ title: display_date(event), class: event.tags.join(' ') }
  - if event.locality?
    %em.locality.fa.fa-globe
  = link_to event do
    %strong.city{ title: event.address }= event.city || event.region
    = event.title
    - if event.repeat&.positive?
      %em.fa.fa-redo-alt{ title: event.schedule }

app/views/events/_form.html.haml
= form_for event, url: { action: event.new_record? ? :create : :update } do |f|
  - if event.persisted?
    = f.hidden_field :lock_version
    - if controller_name == 'events'
      = hidden_field_tag :secret, params[:secret]

  - if event.errors.any?
    #flash-messages
      - event.errors.full_messages.each do |msg|
        %p.flash.alert= msg

  .field.title.required
    = f.label :title
    = f.text_field :title, required: true, placeholder: t('.title_helper')
  .field.start_time.required
    = f.label :start_time
    = f.datetime_field :start_time, required: true,
                                    min: [event.start_time || 1.day.ago, 1.day.ago.change(hour: 0)].min,
                                    max: 1.year.from_now.change(hour: 0),
                                    placeholder: 'YYYY-MM-DDTHH:MM'
  .field.end_time.required
    = f.label :end_time
    = f.datetime_field :end_time, required: true,
                                  min: [event.start_time || 1.day.ago, 1.day.ago.change(hour: 0)].min,
                                  max: 1.year.from_now.change(hour: 0),
                                  placeholder: 'YYYY-MM-DDTHH:MM'

  .field.place_name
    = f.label :place_name
    = f.text_field :place_name
  .helper
    :markdown
      #{t '.address_helper_html'}
  .field.address
    = f.label :address
    = f.text_field :address, list: :addresses
    %datalist#addresses
      - Event.group(:address).order('1 desc').count.each do |r|
        %option= r[0]
  .field.city
    = f.label :city
    = f.text_field :city, list: :cities
    %datalist#cities
      - Event.group(:city).order('1 desc').count.each do |r|
        %option= r[0]
  .field.region.required
    = f.label :region, for: "event_region_id_#{params[:region]}"
    = render partial: '/regions/selector', locals: { f: f }
  .field.locality
    = f.label :locality
    %span.radios
      = f.radio_button :locality, 0
      = f.label 'locality_0' do
        %em.fa.fa-shield-alt
        = t 'attributes.locality_0'
      = f.radio_button :locality, 1
      = f.label 'locality_1' do
        %em.fa.fa-globe
        = t 'attributes.locality_1'

  .field.description.required{ title: t('.description_helper') }
    = f.label :description
    = f.text_area :description, class: :description

  .field.url{ title: t('.url_helper') }
    = f.label :url
    = f.url_field :url, placeholder: 'Ex: https://april.org'
  .field.contact{ title: t('.contact_helper') }
    = f.label :contact
    = f.email_field :contact
  .field.submitter.required{ title: t('.submitter_helper') }
    = f.label :submitter
    = f.email_field :submitter, required: true

  .field.tags{ title: t('.tags_helper') }
    = f.label :tags, for: 'event_tag_list_tag'
    = f.text_field :tag_list, value: f.object.tag_list.to_s
  .helper
    :markdown
      #{t '.tags_helper_html', default: nil}

  - unless event.moderated?
    .field.repeat{ title: t('.repeat_helper') }
      = f.label :repeat
      = f.number_field :repeat, in: 0..40
    .field.rule.required{ title: t('.rule_helper') }
      = f.label :rule
      %span.radios
        - Event::RULES.each do |rule|
          = f.radio_button :rule, rule
          = f.label "rule_#{rule}",
                    t(rule, scope: 'activerecord.attributes.event.rule_values')

  .actions
    = f.button formaction: url_for(action: event.new_record? ? :preview_create : :preview) do
      %em.fa.fa-eye
      = t '.visualise'
    = f.button do
      %em.fa.fa-check
      = t '.save'

app/views/events/cancel.html.haml
%h2
  %em.fa.fa-trash-alt
  = t '.title'

- if @event.moderated?
  %h3.warning= t '.already_moderated'

%fieldset
  = form_for @event, method: :delete do |f|
    = hidden_field_tag :secret, params[:secret]
    %h2= t '.confirm'

    .field.reason
      = f.label :reason
      = f.text_area :reason, cols: 40, rows: 5

    .actions
      = link_to @event do
        %em.fa.fa-arrow-left
        = t '.ko'
      = f.button do
        %em.fa.fa-check
        = t '.ok'

%fieldset
  %legend= Event.model_name.human
  = render template: '/events/show'

app/views/events/edit.html.haml
%h2
  %em.fa.fa-edit
  = t '.title'

- if @event.moderated?
  %h3.warning
    %em.fa.fa-exclamation-triangle
    = t '.warning'

%fieldset
  %legend
    %em.fa.fa-eye
    = t '.preview'
  = render template: '/events/show'

%fieldset
  %legend
    %em.fa.fa-edit
    = t '.edit'
  = render '/events/form', event: @event

app/views/events/index.html.haml
- if params[:year]
  %header.calendar-heading.year
    = link_to '<<', { year: params[:year].to_i - 1 },
              'aria-label': t('simple_calendar.previous', default: 'Previous')
    %h2.calendar-title= params[:year]
    = link_to '>>', { year: params[:year].to_i + 1 },
              'aria-label': t('simple_calendar.next', default: 'Next')

  - (1..12).each do |i|
    - params[:start_date] = "#{params[:year]}-#{i}-01"

    = month_calendar do |date|
      - capture_haml do
        .day_number= date.day
        %ul.events.fa-ul= render month_events(@events, date)

- else
  -# One month calendar
  = month_calendar events: @events do |date, events|
    - capture_haml do
      .day_number= date.day
      %ul.events.fa-ul= render events

.links
  - p = params.permit :city, :region, :tag, near: {}
  = t '.calendar_in_html',
      rss: link_to('RSS', p.merge(format: :rss)),
      webcal: link_to('webcal',
                      events_url(protocol: 'webcal', format: :ics, params: p)),
      ical: link_to('iCal', p.merge(format: :ics))

:plain
  #{t '.banner_html', default: ''}

- events_meta

app/views/events/index.ics.haml
:ruby
  require 'icalendar/tzinfo'

  # Create a calendar with some events
  cal = Icalendar::Calendar.new
  @events.each do |event|
    tzid = event.region.tzid || 'Z'

    # Declare the timezone if it's not already in the calendar
    if cal.timezones.none? { |t| tzid == t.tzid }
      # Only add this zone once
      begin
        tz = TZInfo::Timezone.get tzid
        timezone = tz.ical_timezone event.start_time
        cal.add_timezone timezone
      rescue TZInfo::InvalidTimezoneIdentifier
        puts "Invalid timezone identifier: #{tzid}"
      end
    end

    cal.event do |e|
      e.dtstamp   = Icalendar::Values::DateTime.new event.decision_time, tzid: tzid
      e.dtstart   = Icalendar::Values::DateTime.new event.start_time, tzid: tzid
      e.dtend     = Icalendar::Values::DateTime.new event.end_time, tzid: tzid

      e.uid         = "#{event.id}@#{request.domain(3)&.remove 'www.'}"
      e.summary     = event.title
      e.description = to_markdown event.description
      e.location    = event.full_address
      e.url         = event.url
      e.organizer   = "mailto:#{event.contact}"
      e.x_alt_desc  = Icalendar::Values::Text.new event.description, FMTTYPE: 'text/html'
    end
  end

  cal.publish

!= cal.to_ical

app/views/events/new.html.haml
%h2
  %em.fa.fa-edit
  = title t '.title'

- if @event.description
  %fieldset
    %legend
      %em.fa.fa-eye
      = t '.preview'
    = render template: '/events/show'

- else
  :markdown
    #{t '.subtitle'}

  #advises
    :markdown
      #{t '.advises'}

%fieldset
  %legend
    %em.fa.fa-plus
    = t '.edit'
  = render 'form', event: @event

app/views/events/show.html.haml
- event_meta @event

- if @event.tag_list.to_s.include? 'libre-en-fete'
  = t 'link', scope: 'layouts.context'
  %a(href='https://www.libre-en-fete.net')
    = image_tag 'libre-en-fete.png', width: '180', height: '60',
                                     alt: 'Libre en Fête',
                                     style: 'vertical-align: middle'

- elsif @event.tag_list.include? 'linux-presentation-day'
  = t 'link', scope: 'layouts.context'
  %a(href='http://www.linux-presentation-day.org')
    = image_tag 'linux-presentation-day.png', width: '150', height: '75',
                                              alt: 'Linux presentation day',
                                              style: 'vertical-align: middle'

%h2
  - if @event.locality?
    %em.locality.fa.fa-globe{ title: t('attributes.locality_1') }
  - else
    %em.locality.fa.fa-shield-alt{ title: t('attributes.locality_0') }
  - if @event.city?
    %em.city{ title: @event.full_address }= @event.city
  = title @event.title

= render 'aside', event: @event if [controller_name, action_name] == %w[events show]

%p= display_date @event

%p.full_address
  = [@event.place_name,
     @event.address,
     @event.city,
     t(@event.region&.code.presence,
       scope: :countries,
       default: @event.region)].compact.join(', ')

- if @event.latitude && @event.longitude
  .event#map{ data: { url: maps_path(format: :json),
                      latitude: @event.latitude, longitude: @event.longitude } }

- elsif controller.action_name != 'show' && @event.address.present?
  %em.fa.fa-compress
  %em
    = t '.noMap'
    %a{ target: '_blank',
        href: "https://osm.org/search?query=#{@event.full_address}" }
      = image_tag 'osm_logo.svg', alt: 'OSM logo', width: '32px'

.description
  = description sanitize @event.description,
                         tags: %w[p h1 h2 h3 h4 br table tr th td ul ol li a strong b em i img sub sup span blockquote],
                         attributes: %w[href src width height style title name id]

%h3
  %em.fa.fa-info-circle
  = t '.infos'
%dl
  - if @event.url.present?
    %dt.url
      %em.fa.fa-external-link-alt
      = Event.human_attribute_name :url
    %dd
      = link_to @event.url, @event.url
  - if @event.contact.present?
    %dt.contact
      %em.fa.fa-envelope
      = Event.human_attribute_name :contact
    %dd
      = mail_to @event.contact, nil,
                encode: (request.format == 'text/html' ? :javascript : nil),
                replace_at: ' CHEZ ', replace_dot: ' POINT '
  - if @event.tag_list.any?
    %dt.tags
      %em.fa.fa-tags
      = Event.human_attribute_name :tags
    %dd
      - @event.tag_list.each do |tag|
        = link_to tag, tag_path(tag), rel: :tag

- if @event.repeat&.positive? && @event.rule
  %h3
    %em.fa.fa-redo-alt
    = @event.schedule

  - if @event.moderated?
    %ul
      %li= link_to_unless_current @event.event || @event, @event.event || @event
      - (@event.event || @event).events.each do |e|
        %li= link_to_unless_current e, e

app/views/events/show.ics.haml
:ruby
  require 'icalendar/tzinfo'

  # Create a calendar with one event
  cal = Icalendar::Calendar.new
  tzid = @event.region.tzid || 'Z'
 
  # Declare the timezone if it's not already in the calendar
  if cal.timezones.none? { |t| tzid == t.tzid }
    # Only add this zone once
    begin
      tz = TZInfo::Timezone.get tzid
      timezone = tz.ical_timezone @event.start_time
      cal.add_timezone timezone
    rescue TZInfo::InvalidTimezoneIdentifier
      puts "Invalid timezone identifier: #{tzid}"
    end
  end

  cal.event do |e|
    e.dtstamp   = Icalendar::Values::DateTime.new @event.decision_time, tzid: tzid
    e.dtstart   = Icalendar::Values::DateTime.new @event.start_time, tzid: tzid
    e.dtend     = Icalendar::Values::DateTime.new @event.end_time, tzid: tzid

    e.uid         = "#{@event.id}@#{request.domain(3)&.remove 'www.'}"
    e.summary     = @event.title
    e.description = to_markdown @event.description
    e.location    = @event.full_address
    e.url         = @event.url
    e.organizer   = "mailto:#{@event.contact}"
    e.x_alt_desc  = Icalendar::Values::Text.new @event.description, FMTTYPE: 'text/html'
  end

  cal.publish

!= cal.to_ical

app/views/events/show.text.haml
==============================================================================
!= display_attr @event, :title
!= display_attr @event, :start_time, l(@event.start_time, format: :at)
!= display_attr @event, :end_time, l(@event.end_time, format: :at)
- if @event.place_name?
  != display_attr @event, :place_name
- if @event.address?
  != display_attr @event, :address
- if @event.city?
  != display_attr @event, :city
!= display_attr @event,
               :region,
               t(@event.region&.code.presence, scope: :countries, default: @event.region)
!= display_attr @event, :locality, t("attributes.locality_#{@event.locality}")
- if @event.url?
  != display_attr @event, :url
- if @event.contact.present?
  != display_attr @event, :contact
- if @event.tag_list.present?
  != display_attr @event, :tags, @event.tag_list
- if @event.repeat&.positive?
  = display_attr @event, :repeat
  = display_attr @event,
                 :rule,
                 t(@event.rule, scope: 'activerecord.attributes.event.rule_values')
\
!= to_markdown @event.description, 78
==============================================================================