config/routes.rb
Rails.application.routes.draw do
  get 'actus', to: 'actus#index'
  get 'stats', to: 'stats#index'

  resources :events do
    get :cancel, on: :member
    get :preview, on: :collection, to: 'events#preview_create'
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, on: :member
    get :refuse, on: :member
    get :validate, on: :member
    post :preview, on: :collection, to: 'orgas#preview_create'
    patch :preview, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',
        as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/views/layouts/_context.html.haml
-# Used in pages header

- unless params[:near].present? && params[:near][:location].present?
  #near-me
    %ul.near-me
      %li
        %a.near-me(href="?near[distance]=10&near[location]=[me]")
          %em.fa.fa-arrows-alt-h
          10km
      %li
        %a.near-me(href="?near[distance]=100&near[location]=[me]")
          %em.fa.fa-arrows-alt-h
          100km
      %li
        %a.near-me(href="?near[distance]=1000&near[location]=[me]")
          %em.fa.fa-arrows-alt-h
          1000km
    %a.near-me(href="?near[distance]=1&near[location]=[me]")
      %em.fa.fa-street-view
      = t '.nearMe'

- if params[:orga].present? && params[:orga].is_a?(String)
  %h2.context.orga
    %em.fa.fa-users
    = Orga.find params[:orga]
    %a(href="?orga=" aria-label="#{t '.remove'}")
      %em.fa.fa-times

- if params[:near].present? && params[:near][:location].present?
  %h2.context.near
    %em.fa.fa-map-pin
    = params[:near][:location]
    - if params[:near][:distance].present?
      %em.fa.fa-arrows-alt-h
      = params[:near][:distance]
      km
    %a(href="?near=" aria-label="#{t '.remove'}")
      %em.fa.fa-times

- if params[:region].present? && params[:region].is_a?(String)
  - region = Region.find_by id: params[:region]
  - if region.present?
    %h2.context.region
      = flag_icon region&.flag
      = t region&.code.presence, scope: :countries, default: region
      %a(href="?region=" aria-label="#{t '.remove'}")
        %em.fa.fa-times

- if params.include? :tag
  %h2.context.tag
    %em.fa.fa-tag
    = params[:tag]
    %a(href="?tag=" aria-label="#{t '.remove'}")
      %em.fa.fa-times

app/views/layouts/_flash.html.haml
#flash-messages
  - flash.each do |key, value|
    .flash(class="#{key}")= raw value

app/views/layouts/_version.html.haml
- versions = (@event || @orga).versions

- if versions.empty?
  %p No history

- else
  %dl
    %dt When
    %dd= l versions.last.created_at, format: :at
    %dt What
    %dd
      version
      = versions.length

    - who = versions.last.whodunnit
    - if who.present?
      %dt Who
      %dd= User.find(versions.last.whodunnit).email

    - if versions.length.to_i > 1
      %hr
      - if params[:version].to_i > 1 || !params[:version]
        %dt
        %dd= link_to t('active_admin.previous'),
          { version: (params[:version] || versions.length).to_i - 1 }

    - if params[:version]
      %dl
        %dt When:
        %dd= l versions[(params[:version].to_i - 1)].created_at, format: :at

        %dt What:
        %dd
          version
          = params[:version]

        - who = versions[(params[:version].to_i - 1)].whodunnit
        - if who.present?
          %dt Who:
          %dd= User.find(who).email

        %dt
        %dd= link_to 'Go to current version'

app/views/layouts/application.html.haml
!!! 5
/[if IE]
%html.no-js{ lang: I18n.locale, class: params[:iframe] ? 'iframe' : '' }
  %head
    %meta(charset='utf-8')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    %meta(name='referrer' content='same-origin')
    %meta(name='robots' content='index, follow')

    = display_meta_tags site: t('.title')

    = favicon_link_tag '/favicon.ico'
    = favicon_link_tag 'baby_gnu_adl.png', rel: 'apple-touch-icon', type: 'image/png'
    = auto_discovery_link_tag :rss,
                              { controller: '/events', format: :rss },
                              title: Event.model_name.human.pluralize
    = auto_discovery_link_tag :rss,
                              { controller: '/orgas', format: :rss },
                              title: Orga.model_name.human.pluralize
    = auto_discovery_link_tag :rss,
                              { controller: '/actus', format: :rss },
                              title: Actu.model_name.human.pluralize
    - if ['events', 'orgas'].include?(controller_name) && action_name == 'show'
      %script(type='application/ld+json')
        != render template: "#{controller_name}/show", formats: :jsonld

    = stylesheet_link_tag 'application', media: 'all',
                                         'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload',
                                            defer: true
    = csrf_meta_tags

  - sub = request.domain ? request.domain(3).remove('www.').split('.')[0] : ''
  %body{ class: [sub, controller_name, action_name, params[:tag]] }
    %header.top
      %ul.digest
        - if @events_digest_count&.positive?
          %li.events
            = link_to root_path anchor: current_page?(root_path) && 'content' do
              = t '.events_html', count: @events_digest_count
        - if @orgas_digest_count&.positive?
          %li.orgas
            = link_to orgas_path anchor: current_page?(orgas_path) && 'content' do
              = t '.orgas_html', count: @orgas_digest_count
        - if @actus_digest_count&.positive?
          %li.actus
            = link_to actus_path anchor: current_page?(actus_path) && 'content' do
              = t '.actus_html', count: @actus_digest_count

      = image_tag ENV.fetch('ADL_LOGO', 'baby_gnu_adl.png'),
                  alt: '', class: :logo
      %h1= link_to_unless_current t('.title'), root_path
      %p.subtitle= t '.subtitle'

    = render 'layouts/flash', flash: flash if flash.present?

    %main#content
      = render partial: '/layouts/context' if action_name == 'index'

      = yield

    %footer.bottom
      %nav
        = link_to new_event_path do
          %em.fa.fa-pencil-alt
          = t '.propose'
        = link_to new_orga_path do
          %em.fa.fa-users
          = t '.propose_orga'
        %br/
        = link_to page_path('filter') do
          %em.fa.fa-search
          = t '.search'
        = link_to maps_path do
          %em.fa.fa-map
          = t '.map'
        - if @orgas_digest_count&.positive?
          = link_to orgas_path do
            %em.fa.fa-users
            = Orga.model_name.human.pluralize
        - if @actus_digest_count&.positive?
          = link_to actus_path do
            %em.fa.fa-newspaper
            = Actu.model_name.human.pluralize
        = link_to page_path('infos') do
          %em.fa.fa-info
          = t '.infos'
        = link_to stats_path do
          %em.fa.fa-signal
          = t '.stats'
        = link_to page_path('contact') do
          %em.fa.fa-envelope
          = t '.contact'
        = link_to moderations_path do
          %em.fa.fa-gavel
          = t '.moderation'